# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20160804_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCharter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('prerequisites', models.CharField(blank=True, max_length=50)),
                ('objective', models.TextField()),
                ('scope', models.TextField()),
                ('test_notes', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Persona')),
                ('versions', models.ManyToManyField(to='main.Version')),
            ],
        ),
    ]
