# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testcharter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('test_cases', models.ManyToManyField(to='main.TestCase')),
                ('test_charters', models.ManyToManyField(to='main.TestCharter')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Version')),
            ],
        ),
    ]
