# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testgroup',
            name='test_cases',
            field=models.ManyToManyField(blank=True, to='main.TestCase'),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='test_charters',
            field=models.ManyToManyField(blank=True, to='main.TestCharter'),
        ),
    ]
