# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20160810_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('Not Run', 'Not Run'), ('Pass', 'Pass'), ('Fail', 'Fail'), ('N/A', 'N/A')], max_length=15)),
                ('result_notes', models.TextField()),
                ('execution_date', models.DateTimeField(editable=False)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestCase')),
                ('test_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TestGroup')),
                ('tester', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
