# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='affected_test_cases',
            field=models.ManyToManyField(blank=True, null=True, to='main.TestCase'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='affected_versions',
            field=models.ManyToManyField(blank=True, null=True, related_name='affected_versions', to='main.Version'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='defect',
            name='fixed_versions',
            field=models.ManyToManyField(blank=True, null=True, related_name='fixed_version', to='main.Version'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testcharter',
            name='prerequisites',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='test_cases',
            field=models.ManyToManyField(blank=True, null=True, to='main.TestCase'),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='test_charters',
            field=models.ManyToManyField(blank=True, null=True, to='main.TestCharter'),
        ),
        migrations.AlterField(
            model_name='testsession',
            name='areas_tested',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
