# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='defect',
            field=models.ManyToManyField(blank=True, null=True, to='main.Defect'),
        ),
    ]
