# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20160822_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='defect',
            field=models.ManyToManyField(blank=True, to='main.Defect'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='test_result',
            field=models.ManyToManyField(blank=True, to='main.TestResult'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='test_session',
            field=models.ManyToManyField(blank=True, to='main.TestSession'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='affected_test_cases',
            field=models.ManyToManyField(blank=True, to='main.TestCase'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='affected_versions',
            field=models.ManyToManyField(blank=True, related_name='affected_versions', to='main.Version'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='fixed_versions',
            field=models.ManyToManyField(blank=True, related_name='fixed_version', to='main.Version'),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='test_cases',
            field=models.ManyToManyField(blank=True, to='main.TestCase'),
        ),
        migrations.AlterField(
            model_name='testgroup',
            name='test_charters',
            field=models.ManyToManyField(blank=True, to='main.TestCharter'),
        ),
    ]
